server:
  port: 8080 # 配置端口
  servlet:
    context-path: / # 项目启动地址为 localhost:8080/

spring:
  datasource: # set database config
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/record?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 87096429

mybatis:
  config-location: classpath:/mybatis-config.xml

